import { parseSiteContent } from '@/content/siteContentSchema';

function media(url, alt = '') {
  return { path: url, url, alt };
}

export const defaultSiteContent = parseSiteContent({
  settings: {
    siteName: 'Dundee Elim Church',
    shortName: 'Dundee Elim',
    tagline: 'Discover Your Purpose',
    footerDescription: 'A Spirit-filled community in Dundee, Scotland. Everyone is welcome.',
    contact: {
      email: 'dundee.elim@gmail.com',
      phoneDisplay: '01382 226020',
      phoneHref: '01382226020',
      addressLine1: '40-42 Dudhope Crescent Road',
      addressLine2: 'Dundee, DD1 5RR',
      addressShort: '40-42 Dudhope Crescent Road, Dundee DD1 5RR',
    },
    links: {
      mapsUrl: 'https://maps.google.com/?q=40-42+Dudhope+Crescent+Road,+Dundee+DD1+5RR',
      mapsEmbedUrl: 'https://maps.google.com/maps?q=56.46389184910621,-2.9779949498050002&hl=en&z=17&output=embed',
      youtubeChannelId: 'UCFMgRFVdYMzj0AczMJPpZvA',
      youtubeUrl: 'https://www.youtube.com/channel/UCFMgRFVdYMzj0AczMJPpZvA',
      facebookUrl: 'https://www.facebook.com/dundeeelim',
      elimUrl: 'https://elim.org.uk',
      onlineGivingUrl: 'http://elim.paythru.com/t/EiVVVTiS',
      giftAidFormUrl: 'https://d3hgrlq6yacptf.cloudfront.net/5f16ff2003262/content/pages/documents/1583858527556960665.pdf',
      safeguardingPolicyUrl: 'https://www.dundee-elim.org.uk/content/pages/documents/safeguarding-policy-2022-23.pdf',
      safeguardingConcernUrl: 'https://elim.myiknowchurch.co.uk/embed/safeguarding/forms/WU5KWE1ZaExBdWxESDROQmszN0RiWjNPUmRjbi9RUmNOakVQVGYvWlpBRW9SQ05lcUNBSnpnOGdjdmg1',
      elimSafeguardingUrl: 'https://www.elim.org.uk/Articles/435374/Safeguarding.aspx',
    },
    branding: {
      logo: media('/images/branding/dundee-elim-logo.png', 'Dundee Elim Church logo'),
    },
    seo: {
      siteUrl: 'https://www.dundee-elim.org.uk',
      defaultTitle: 'Dundee Elim Church – Discover Your Purpose',
      defaultDescription: 'Dundee Elim is a Spirit-filled, Bible-based church in Dundee, Scotland. Join us every Sunday at 10:30 AM. Everyone is welcome.',
      defaultImage: media('/images/branding/dundee-elim-logo.png', 'Dundee Elim Church logo'),
    },
  },
  home: {
    seo: {
      title: '',
      description: 'Dundee Elim is a Spirit-filled, Bible-based church in Dundee, Scotland. Join us every Sunday at 10:30 AM. Everyone is welcome.',
    },
    hero: {
      eyebrow: 'Welcome to Dundee Elim Church',
      titleLead: 'Discover',
      titleHighlight: 'Your Purpose',
      description: "A Spirit-filled, welcoming community in the heart of Dundee. Join us every Sunday and experience God's love, power and purpose for your life.",
      primaryCtaLabel: 'Plan Your Visit',
      primaryCtaPath: '/about',
      secondaryCtaLabel: 'Watch Sermons',
      secondaryCtaPath: '/sermons',
      serviceBadgeLabel: 'Next Service',
      serviceBadgeDay: 'Sunday',
      serviceBadgeTime: '10:30 AM',
      scrollLabel: 'Scroll',
      slides: [
        { image: media('/images/home/congregation-1.jpg', 'Congregation gathered together'), caption: 'Join Us Every Sunday — 10:30 AM' },
        { image: media('/images/home/worship-1.jpg', 'Worship at Dundee Elim'), caption: 'Spirit-Filled Worship' },
        { image: media('/images/home/congregation-2.jpg', 'A full church service'), caption: 'A Full House & Full Hearts' },
        { image: media('/images/home/people-6.jpg', 'People in community'), caption: 'Community & Belonging' },
        { image: media('/images/home/congregation-4.jpg', 'Church family together'), caption: 'Lives Being Transformed' },
      ],
    },
    quickInfo: {
      items: [
        { kind: 'service', title: 'Sunday Service', sub: '10:30 AM every week' },
        { kind: 'location', title: '40-42 Dudhope Crescent Rd', sub: 'Dundee DD1 5RR' },
        { kind: 'kids', title: 'Kids Club', sub: 'Primary & Pre-school' },
      ],
    },
    pastors: {
      eyebrow: 'Our Pastors',
      titleLead: 'A Warm Welcome',
      titleHighlight: 'Awaits You',
      paragraphs: [
        'We are Pastor Steven and Annette Holmes and we lead Dundee Elim Church. We believe in the power of community, the transforming work of the Holy Spirit, and that every person has a God-given purpose to discover.',
        "Whether you're exploring faith for the first time or looking for a church home — you are welcome here. Come as you are. Everyone belongs.",
      ],
      image: media('/images/home/pastors-home.jpg', 'Pastor Steven and Annette Holmes'),
      imageTitle: 'Pastor Steven & Annette Holmes',
      imageSubtitle: 'Lead Pastors, Dundee Elim',
      stats: [
        { value: '20+', label: 'Nationalities' },
        { value: '200+', label: 'Members' },
        { value: '30+', label: 'Years' },
        { value: '100+', label: 'Sermons' },
      ],
      ctaLabel: 'Learn more about us',
      ctaPath: '/about',
    },
    beliefs: {
      eyebrow: 'Our Foundation',
      title: 'What We Believe',
      items: [
        { kind: 'worship', title: 'Spirit-Filled Worship', description: 'We believe in the presence and power of the Holy Spirit, expressed freely in our worship and life together.' },
        { kind: 'bible', title: 'Bible-Based Teaching', description: "God's Word is our foundation. Our preaching equips you to grow in faith and live out God's calling." },
        { kind: 'community', title: 'Loving Community', description: "We are a diverse, multicultural family united by Christ's love. Every person is welcomed, valued and loved." },
      ],
    },
    gallery: {
      eyebrow: 'Our Community',
      title: 'Life at Dundee Elim',
      topImages: [
        media('/images/home/grid-1.jpg', 'Community life at Dundee Elim'),
        media('/images/home/grid-2.jpg', 'Church gathering'),
        media('/images/home/grid-5.jpg', 'Worship moment'),
      ],
      bottomImages: [
        media('/images/home/grid-4.jpg', 'Church family fellowship'),
        media('/images/home/grid-6.jpg', 'Congregation together'),
      ],
    },
    media: {
      eyebrow: 'Media',
      title: 'Latest from YouTube',
      subscribeLabel: 'Subscribe',
      viewAllLabel: 'View all sermons',
      viewAllPath: '/sermons',
    },
    weeklyRhythm: {
      title: 'Weekly Rhythm',
      items: [
        { day: 'Sunday', time: '10:30 AM', name: 'Morning Service' },
        { day: 'Sunday', time: 'During Service', name: 'Kids Club' },
        { day: 'Wednesday', time: '7:00 PM', name: 'Prayer Meeting' },
        { day: 'Thursday', time: '4:30 PM', name: 'Youth (Ninety Nine) - Fortnightly' },
        { day: 'Sunday', time: '6:30 PM', name: 'Young Adults - Monthly' },
        { day: 'Tuesday', time: '7:00 PM', name: 'Connect Groups' },
      ],
      footerLabel: 'All events',
      footerPath: '/events',
    },
    prayerRequest: {
      eyebrow: "We're Here For You",
      title: 'Submit a Prayer Request',
      description: 'Our pastoral team prays over every request. You can choose to keep your request private.',
      successTitle: 'We’re Praying For You',
      successDescription: 'Your request has been received by the pastoral team.',
      resetLabel: 'Submit another request',
      privacyLabel: 'Keep this request private',
      privacyDescription: 'Only the pastoral team will see it',
      submitLabel: 'Send Prayer Request',
    },
    cta: {
      title: 'Ready to Join Us?',
      description: "We'd love to meet you. Come along this Sunday — 10:30 AM — or get in touch with any questions.",
      primaryLabel: 'Get In Touch',
      primaryPath: '/contact',
      secondaryLabel: 'Get Directions',
      secondaryUrl: 'https://maps.google.com/?q=40-42+Dudhope+Crescent+Road,+Dundee+DD1+5RR',
    },
  },
  about: {
    seo: {
      title: 'About Us',
      description: 'Learn about Dundee Elim Church, our pastors Steven and Annette Holmes, what to expect on a Sunday, and how to find us.',
    },
    header: {
      eyebrow: 'About Us',
      titleLead: 'Who We',
      titleHighlight: 'Are',
      description: 'Dundee Elim is a Spirit-filled, Bible-based church in the heart of Dundee, part of the Elim Pentecostal Churches network.',
      image: media('/images/shared/worship-service.jpg', 'Worship at Dundee Elim'),
    },
    pastors: {
      eyebrow: 'Leadership',
      titleLead: 'Pastor Steven &',
      titleHighlight: 'Annette Holmes',
      paragraphs: [
        'Pastor Steven and Annette Holmes lead Dundee Elim Church with a heart for people and a passion for the presence of God. They are committed to building a community where every person can discover their God-given purpose.',
        "Under their leadership, the church has grown into a diverse, multicultural congregation that reflects the richness of God's family. Their vision is to see Dundee impacted by the transforming power of the Gospel.",
      ],
      image: media('/images/about/pastors-about.jpg', 'Pastor Steven and Annette Holmes'),
    },
    sundayExpectations: {
      title: 'What to Expect on a Sunday',
      description: 'Our Sunday services are informal, Spirit-led gatherings where everyone is welcome just as they are.',
      items: [
        { number: '01', title: 'A Warm Welcome', description: 'You will be greeted at the door by friendly stewards. Hugs are optional — just say if you prefer a handshake!' },
        { number: '02', title: 'Worship', description: 'We sing several songs with words on the screen. Feel free to stand, sit, or engage however you are comfortable.' },
        { number: '03', title: 'Announcements', description: "You'll hear what's happening in the church that week, so you can get involved." },
        { number: '04', title: 'Kids Club', description: 'Primary and pre-school children head to their own groups during the service. All children must be signed in and out.' },
        { number: '05', title: 'The Word', description: "The preacher shares from God's Word — usually around 25 minutes. Relevant, practical and inspiring." },
        { number: '06', title: 'Tea & Coffee', description: "After the service, join us for refreshments in the back room. It's a great time to connect and meet new people." },
      ],
      note: 'Communion is served periodically and we always use Gluten Free bread. Accessible ramp available at the back of the building.',
    },
    gettingHere: {
      title: 'Getting Here',
      cards: [
        { kind: 'address', title: 'Address', description: '40-42 Dudhope Crescent Road\nDundee DD1 5RR', linkLabel: 'Open in Google Maps', linkUrl: 'https://maps.google.com/?q=40-42+Dudhope+Crescent+Road,+Dundee+DD1+5RR' },
        { kind: 'car', title: 'By Car', description: 'Limited parking on site in the lane next to the church, plus free on-street parking nearby until 1pm on Sundays.', linkLabel: '', linkUrl: '' },
        { kind: 'bus', title: 'By Bus', description: 'A short walk from nearby stops in town. Use the traffic lights near the Church to cross safely.', linkLabel: '', linkUrl: '' },
      ],
      mapEmbedUrl: 'https://maps.google.com/maps?q=56.46389184910621,-2.9779949498050002&hl=en&z=17&output=embed',
    },
    network: {
      title: 'Part of Elim Pentecostal Churches',
      description: "Dundee Elim is part of Elim Pentecostal Churches, one of the UK's largest Pentecostal denominations with over 550 churches.",
      linkLabel: 'Visit Elim.org.uk',
      linkUrl: 'https://elim.org.uk',
    },
  },
  sermons: {
    seo: {
      title: 'Sermons & Teachings',
      description: 'Watch or listen to sermons from Dundee Elim Church.',
    },
    header: {
      eyebrow: 'Media',
      titleLead: 'Sermons &',
      titleHighlight: 'Teachings',
      description: 'Watch or listen to messages from Dundee Elim. Be encouraged, challenged and equipped in your faith.',
      image: media('/images/shared/worship-service.jpg', 'Worship at Dundee Elim'),
    },
    subscribeCard: {
      title: 'Dundee Elim on YouTube',
      description: 'Subscribe for new sermons every week',
      linkLabel: 'Subscribe',
    },
    tabs: {
      live: 'Live',
      video: 'Video',
      audio: 'Audio',
    },
    live: {
      liveTitle: "We're Live Now!",
      offlineTitle: 'Latest Stream',
      liveDescription: 'Join us live right now!',
      offlineDescription: 'We go live every Sunday at 10:30 AM.',
      buttonLabel: 'Open on YouTube',
    },
    videoSection: {
      title: 'Latest Sermon',
    },
    videoSermons: [
      { id: 'APW7puyritw', title: 'The Serving Church', speaker: 'Ps. Steven Holmes', series: 'How to be The Church Series', date: '2026-03-29', description: 'A message on serving one another and reflecting the heart of Jesus in everyday church life.' },
      { id: '_Nj98cJ9wdY', title: 'The Generous Church', speaker: 'Andrew Bennett', series: 'How to be The Church Series', date: '2026-03-22', description: 'A call to be a people marked by open hands, open hearts and a generous spirit.' },
      { id: 'axd2Lfm7RoA', title: 'Fearless Church', speaker: 'Dr. Lanre Lewis', series: 'How to be The Church Series', date: '2026-03-16', description: 'Encouragement to live with bold faith and confidence in the mission God has given His church.' },
      { id: 'auK2SUknPLU', title: 'Connected Church', speaker: 'Dereck Grant', series: 'How to be The Church Series', date: '2026-03-09', description: 'A practical message on belonging, fellowship and healthy spiritual connection.' },
      { id: 'uJnaqe1a4N0', title: 'Miraculous Church', speaker: 'Stephen Appleton', series: 'How to be The Church Series', date: '2026-03-02', description: 'Looking again at the power of God at work through an expectant and Spirit-filled church.' },
      { id: 'Wa6ZANBgrtM', title: 'Empowered Church', speaker: 'Andrew Bennett', series: 'How to be The Church Series', date: '2026-02-23', description: 'A reminder that the church is meant to live and serve in the strength of the Holy Spirit.' },
      { id: 'JiEo2G9TtlA', title: 'Get Ready Church!', speaker: 'Andrew Bennett', series: 'How to be The Church Series', date: '2026-02-16', description: 'A stirring message about spiritual readiness, expectation and obedience.' },
      { id: '7JKWqc8K428', title: 'Ready or Not?', speaker: 'Ps. Steven Holmes', series: 'Sunday Service', date: '2026-02-09', description: 'A Sunday message urging the church to stay awake, faithful and ready for what God is doing.' },
      { id: 'Wb56QcxoD24', title: 'Your Prayers Are Not Wasted', speaker: 'Ps. Steven Holmes', series: 'Sunday Service', date: '2026-02-02', description: 'Encouragement to keep praying with confidence even when answers seem delayed.' },
    ],
    audioSermons: [],
  },
  events: {
    seo: {
      title: 'Events & Services',
      description: "Stay connected with what's happening at Dundee Elim Church.",
    },
    header: {
      eyebrow: "What's On",
      titleLead: 'Events &',
      titleHighlight: 'Services',
      description: "Stay connected with what's happening at Dundee Elim. There's always something to be part of.",
      image: media('/images/shared/events-congregation.jpg', 'Congregation at Dundee Elim'),
    },
    viewLabels: {
      list: 'List',
      week: 'Week',
      month: 'Month',
    },
    categoryLabels: {
      all: 'All',
      service: 'Service',
      prayer: 'Prayer',
      youth: 'Youth',
      community: 'Community',
      special: 'Special',
    },
    recurringTemplates: [
      {
        title: 'Sunday Morning Service',
        description: "Join us for worship, prayer and God's Word. Kids Club runs during the service for children.",
        location: '40-42 Dudhope Crescent Road, Dundee DD1 5RR',
        category: 'service',
        weekday: 'sunday',
        time: '10:30 AM',
        intervalWeeks: 1,
        startDate: '2026-04-05',
        recurringLabel: 'Every Sunday at 10:30 AM',
      },
      {
        title: 'Prayer Meeting',
        description: 'Mid-week prayer gathering for the whole church family.',
        location: 'Dundee Elim Church',
        category: 'prayer',
        weekday: 'wednesday',
        time: '7:00 PM',
        intervalWeeks: 1,
        startDate: '2026-04-08',
        recurringLabel: 'Every Wednesday at 7:00 PM',
      },
      {
        title: 'Ninety Nine Youth',
        description: 'A welcoming youth night with conversation, faith, fun and practical ways to serve the city.',
        location: 'Dundee Elim Church',
        category: 'youth',
        weekday: 'thursday',
        time: '4:30 PM',
        intervalWeeks: 2,
        startDate: '2026-04-09',
        recurringLabel: 'Every second Thursday at 4:30 PM',
      },
      {
        title: 'Connect Group',
        description: 'Small-group discipleship, prayer and friendship in a more conversational setting.',
        location: 'Various homes across Dundee',
        category: 'community',
        weekday: 'tuesday',
        time: '7:00 PM',
        intervalWeeks: 2,
        startDate: '2026-04-07',
        recurringLabel: 'Most Tuesdays at 7:00 PM',
      },
    ],
    specialEvents: [
      {
        title: 'Welcome Lunch',
        description: 'A relaxed lunch after the service for anyone new to Dundee Elim. Meet the team and get connected.',
        location: 'Dundee Elim Church',
        category: 'community',
        date: '2026-04-19',
        time: '1:00 PM',
      },
      {
        title: 'Young Adults Gathering',
        description: "For ages 17–30. Food, worship and God's Word together on a Sunday evening.",
        location: 'Dundee Elim Church',
        category: 'community',
        date: '2026-04-26',
        time: '6:30 PM',
      },
    ],
  },
  ministries: {
    seo: {
      title: 'Discover',
      description: 'Discover the groups and ministries at Dundee Elim Church.',
    },
    header: {
      eyebrow: 'Get Involved',
      titleLead: 'Something for',
      titleHighlight: 'Everyone',
      description: 'From youth nights to ladies’ ministry, prayer to community meals — discover where you belong.',
      image: media('/images/shared/events-congregation.jpg', 'Congregation at Dundee Elim'),
    },
    items: [
      { title: 'Prayer', tag: 'Discover', summary: 'A church that believes in the power of prayer. We pray individually, corporately, and persistently.', body: '"Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God." — Philippians 4:6\n\nJoin us for our regular prayer gatherings, and check out 21 Days of Prayer.', details: ['Mid-week prayer meetings', 'Nights of worship and intercession', 'Prayer team after services', '21 Days of Prayer'], linkLabel: '21 Days of Prayer', linkUrl: 'https://www.dundee-elim.org.uk/discover/prayer/21-days-of-prayer/', contactEmail: '', contactPhone: '', iconKey: 'heart', theme: 'red' },
      { title: 'Connect Groups', tag: 'Discover', summary: 'Small groups meeting regularly to grow in faith, study the Bible and build community.', body: "Connect Groups meet in smaller settings throughout the week. Currently running through the S.H.A.P.E. Course — You are God's Masterpiece.\n\nSign up today and join us for an adventure that will steer your life towards all that God wants to do in you and through you.", details: ['Small groups across Dundee', 'Currently: SHAPE Course', '6-week sessions', 'Everyone welcome'], linkLabel: 'Sign Up', linkUrl: 'https://dundeeelim.churchsuite.com/events/iv542amp', contactEmail: 'dundee.elim@gmail.com', contactPhone: '07950 959525', iconKey: 'users', theme: 'orange' },
      { title: "Forge - Men's Ministry", tag: 'Discover', summary: 'Forge helps men build a deeper, stronger relationship with God.', body: "We are excited about our Men's Ministry 'Forge'. We seek to help other men forge their relationship with God in a deeper and stronger way, and see men come to know Christ and the new life He gives.", details: ['Regular men’s gatherings', 'Bible study & discipleship', 'Brotherhood & accountability', 'Social events'], linkLabel: '', linkUrl: '', contactEmail: 'dundee.elim@gmail.com', contactPhone: '', iconKey: 'zap', theme: 'blue' },
      { title: 'Ninety Nine - Youth', tag: 'Discover', summary: 'A vibrant youth community for young people to connect, learn, grow, and make a difference.', body: "Join us every second Thursday at 4:30pm. It's a wonderful chance to make new friends, participate in engaging activities and make a difference in the community.", details: ['Every 2nd Thursday at 4:30pm', 'Fun activities & events', 'Mentoring & discipleship', 'Making a community difference'], linkLabel: 'View Calendar', linkUrl: 'https://www.dundee-elim.org.uk/calendar', contactEmail: '', contactPhone: '', iconKey: 'users', theme: 'green' },
      { title: 'EmpowHer - Ladies Ministry', tag: 'Discover', summary: 'EmpowHer is our ladies’ ministry — a community where women are encouraged, equipped and empowered.', body: '"God is within her, she will not fall; God will help her at break of day." — Psalm 46:5\n\nEmpowHer is a space for women to gather, grow in faith, support one another and be empowered to live purposeful lives.', details: ['Ladies events & gatherings', 'Encouragement & support', 'Faith & friendship', 'Growing together in God'], linkLabel: 'View Calendar', linkUrl: 'https://www.dundee-elim.org.uk/calendar', contactEmail: 'dundee.elim@gmail.com', contactPhone: '', iconKey: 'star', theme: 'pink' },
      { title: 'Young Adults', tag: 'Discover', summary: 'For 17–30 year olds. Meet monthly on Sunday evenings to build community around food, worship and God’s Word.', body: "We meet on Sunday evening once a month, 6:30–9:00pm, to build community around food, worship and God's word.\n\nThis term we're exploring what it means to be a disciple that makes disciples.", details: ['Monthly Sunday evenings 6:30–9pm', 'Ages 17–30', 'Food, worship & God’s word', 'Discipleship focus'], linkLabel: '', linkUrl: '', contactEmail: 'dundee.elim@gmail.com', contactPhone: '', iconKey: 'church', theme: 'indigo' },
      { title: 'Alpha Course', tag: 'Community', summary: 'A series of group conversations freely exploring the basics of Christian faith. Everyone welcome.', body: "Dundee Elim Alpha will be running again in 2026.\n\nAlpha is a series of group conversations that freely explore the basics of the Christian faith in an open, friendly environment. Everyone's welcome.", details: ['Running again in 2026', 'Open to everyone', 'Food, video & discussion', 'No pressure environment'], linkLabel: 'Learn more about Alpha', linkUrl: 'https://alpha.org.uk/try-alpha', contactEmail: 'andrew@dundee-elim.org.uk', contactPhone: '', iconKey: 'book-open', theme: 'amber' },
      { title: 'Make Lunch', tag: 'Community', summary: 'Free hot meals for families during school holidays. Community, belonging and meals that matter.', body: 'Make Lunch is an opportunity for families to get together, have fun and have a good hot meal during the school holidays.\n\nEaster 2026 dates:\nWednesday 8th April 2026, 12–2pm\nWednesday 15th April 2026, 12–2pm', details: ['School holiday lunches', 'Ages 0–12 + teenage table', 'Fun activities & crafts', 'Free & open to all'], linkLabel: '', linkUrl: '', contactEmail: '', contactPhone: '07950 959525', iconKey: 'utensils-crossed', theme: 'green' },
      { title: 'Kids Club', tag: 'Children', summary: 'A safe, fun and faith-filled environment for children during the Sunday service.', body: 'Kids Club runs during the Sunday morning service for primary school and pre-school children. We operate a safe sign-in/sign-out system for all children.', details: ['Every Sunday during service', 'Dedicated children’s leaders', 'Bible stories & activities', 'Safe sign-in/sign-out'], linkLabel: '', linkUrl: '', contactEmail: 'dundee.elim@gmail.com', contactPhone: '', iconKey: 'baby', theme: 'yellow' },
      { title: 'Worship Team', tag: 'Serve', summary: 'Our worship team leads Spirit-filled worship every Sunday, creating an atmosphere to encounter God.', body: 'Our worship team leads the church in Spirit-filled worship every Sunday. If you have musical gifts and a heart for worship, we’d love to hear from you.', details: ['Sunday service worship', 'Special worship nights', 'Open to those with musical gifts', 'Contact us to get involved'], linkLabel: '', linkUrl: '', contactEmail: 'dundee.elim@gmail.com', contactPhone: '', iconKey: 'music', theme: 'purple' },
    ],
    photoStrip: [
      media('/images/shared/fellowship.jpg', 'Church fellowship'),
      media('/images/shared/contact-group.jpg', 'Group from Dundee Elim'),
      media('/images/shared/worship-service.jpg', 'Worship service'),
      media('/images/shared/events-congregation.jpg', 'Congregation gathering'),
    ],
  },
  give: {
    seo: {
      title: 'Give',
      description: 'Support the vision of Dundee Elim Church through online giving, standing order, or in person.',
    },
    header: {
      eyebrow: 'Support the Vision',
      titleLead: 'Give',
      titleHighlight: 'Generously',
      quote: '"You do well and excel in every respect — so make sure that you also excel in grace-filled generosity."',
      quoteCitation: '2 Corinthians 8:7 (TPT)',
      image: media('/images/shared/fellowship.jpg', 'Fellowship at Dundee Elim'),
    },
    scripture: {
      quote: '"Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver."',
      citation: '2 Corinthians 9:7',
    },
    methodsTitle: 'Ways to Give',
    methods: [
      { kind: 'online', title: 'Give Online', description: 'Give securely online as a one-off payment or set up regular giving via Paythru.', ctaLabel: 'Give Online', ctaUrl: 'http://elim.paythru.com/t/EiVVVTiS', contactEmail: '', contactPhone: '', addressLines: [] },
      { kind: 'bank', title: 'Standing Order / Bank Transfer', description: 'Contact the church office to set up a standing order or get bank details.', ctaLabel: '', ctaUrl: '', contactEmail: 'dundee.elim@gmail.com', contactPhone: '01382 226020', addressLines: [] },
      { kind: 'inperson', title: 'In Person or Cheque', description: 'Give in person during Sunday services, or send a cheque payable to:', ctaLabel: '', ctaUrl: '', contactEmail: '', contactPhone: '', addressLines: ['Dundee Elim Church', '40 Dudhope Crescent Road', 'Dundee, DD1 5RR'] },
    ],
    giftAid: {
      title: 'Gift Aid',
      description: 'If you are a UK taxpayer, you can boost your giving by 25% at no extra cost through Gift Aid.',
      ctaLabel: 'Download Gift Aid Form',
      ctaUrl: 'https://d3hgrlq6yacptf.cloudfront.net/5f16ff2003262/content/pages/documents/1583858527556960665.pdf',
    },
    impact: {
      title: 'What Your Gift Supports',
      items: [
        { label: 'Sunday Services', icon: '🙏' },
        { label: 'Kids & Youth Ministry', icon: '👦' },
        { label: 'Outreach in Dundee', icon: '🏙️' },
        { label: 'Missions Support', icon: '🌍' },
      ],
    },
    contactCta: {
      title: 'Questions about giving?',
      description: "Get in touch with the church office and we'll be happy to help.",
    },
  },
  contact: {
    seo: {
      title: 'Contact Us',
      description: 'Get in touch with Dundee Elim Church.',
    },
    header: {
      eyebrow: 'Get In Touch',
      titleLead: 'Contact',
      titleHighlight: 'Us',
      description: "We'd love to hear from you — for questions, prayer, or to plan your visit.",
      image: media('/images/shared/contact-group.jpg', 'Church community group'),
    },
    infoCards: [
      {
        kind: 'address',
        title: 'Our Address',
        descriptionLines: ['40-42 Dudhope Crescent Road', 'Dundee, DD1 5RR', 'Scotland, UK'],
        items: [],
        linkLabel: 'Get Directions',
        linkUrl: 'https://maps.google.com/?q=40-42+Dudhope+Crescent+Road,+Dundee+DD1+5RR',
      },
      {
        kind: 'contact',
        title: 'Email & Phone',
        descriptionLines: [],
        items: [
          { label: 'Email', value: 'dundee.elim@gmail.com' },
          { label: 'Phone', value: '01382 226020' },
        ],
        linkLabel: '',
        linkUrl: '',
      },
      {
        kind: 'service',
        title: 'Service Times',
        descriptionLines: [],
        items: [
          { label: 'Sunday Service', value: '10:30 AM' },
          { label: 'Kids Club', value: 'During service' },
        ],
        linkLabel: '',
        linkUrl: '',
      },
    ],
    form: {
      title: 'Send Us a Message',
      successTitle: 'Message Sent!',
      successDescription: "Thank you for getting in touch. We'll get back to you soon.",
      resetLabel: 'Send another message',
      submitLabel: 'Send Message',
    },
    mapEmbedUrl: 'https://maps.google.com/maps?q=56.46389184910621,-2.9779949498050002&hl=en&z=17&output=embed',
  },
  safeguarding: {
    seo: {
      title: 'Safeguarding',
      description: "Dundee Elim Church's commitment to safeguarding children, young people and adults.",
    },
    header: {
      eyebrow: 'Our Commitment',
      titleLead: 'Safe',
      titleHighlight: 'guarding',
      description: 'Creating healthy churches and safe spaces for all — children, young people and adults.',
      image: media('/images/headers/safeguarding.jpg', 'Prayer and safeguarding at Dundee Elim'),
    },
    statement: {
      title: 'Statement of Commitment',
      paragraphs: [
        'Elim is committed to creating healthy churches and safe spaces for all. We recognise the ways in which children and adults can be at risk of harm or abuse, so endeavour to create a culture to minimise opportunities for abuse to occur.',
        'Children rely on adults to keep them safe, therefore all our churches working with children are committed to safeguarding children in their care. We seek to do this by providing a safe, stable, and nurturing environment.',
        'Similarly, within our churches there are adults in need of protection, care and support due to vulnerability. We are aware that within our churches there are relationships of trust, which flourish best within healthy, open and accountable environments.',
        "We firmly believe that safeguarding is everyone's responsibility, and all involved in the life of our churches have a role to play in keeping children, young people and adults safe.",
      ],
    },
    resourcesTitle: 'Key Resources',
    resources: [
      { kind: 'elim', title: 'Elim Safeguarding', description: 'View the national Elim Safeguarding policy and information on the Elim website.', ctaLabel: 'View on Elim.org.uk', ctaUrl: 'https://www.elim.org.uk/Articles/435374/Safeguarding.aspx' },
      { kind: 'report', title: 'Report a Concern', description: 'Use the national reporting form to raise a safeguarding concern within the Elim organisation.', ctaLabel: 'Report a Concern', ctaUrl: 'https://elim.myiknowchurch.co.uk/embed/safeguarding/forms/WU5KWE1ZaExBdWxESDROQmszN0RiWjNPUmRjbi9RUmNOakVQVGYvWlpBRW9SQ05lcUNBSnpnOGdjdmg1' },
      { kind: 'policy', title: 'Our Safeguarding Policy', description: "Read Dundee Elim's full Safeguarding Policy document.", ctaLabel: 'Download Policy PDF', ctaUrl: 'https://www.dundee-elim.org.uk/content/pages/documents/safeguarding-policy-2022-23.pdf' },
    ],
    contact: {
      title: 'Questions or Concerns?',
      description: 'If you have any safeguarding questions or concerns relating to Dundee Elim, please contact us directly.',
      buttonLabel: 'Email safeguarding contact',
    },
  },
});
